In [1]:
#keyboard like nxt word suggestion in healthcare

In [131]:
with open('/content/train.dat', 'r') as f:
    train_content = f.read()

with open('/content/test.dat', 'r') as f:
    test_content = f.read()

print("Content of train.dat:")
print(train_content[:100])

print("\nContent of test.dat:")
print(test_content[:100])

Content of train.dat:
4	Catheterization laboratory events and hospital outcome with direct angioplasty for acute myocardia

Content of test.dat:
Excision of limbal dermoids. We reviewed the clinical files of 10 patients who had undergone excisio


In [139]:
train_content[:3000]

"4\tCatheterization laboratory events and hospital outcome with direct angioplasty for acute myocardial infarction To assess the safety of direct infarct angioplasty without antecedent thrombolytic therapy, catheterization laboratory and hospital events were assessed in consecutively treated patients with infarctions involving the left anterior descending (n = 100 patients), right (n = 100), and circumflex (n = 50) coronary arteries. The groups of patients were similar for age (left anterior descending coronary artery, 59 years; right coronary artery, 58 years; circumflex coronary artery, 62 years), patients with multivessel disease (left anterior descending coronary artery, 55%; right coronary artery, 55%; circumflex coronary artery, 64%), and patients with initial grade 0/1 antegrade flow (left anterior descending coronary artery, 79%; right coronary artery, 84%; circumflex coronary artery, 90%). Cardiogenic shock was present in eight patients with infarction of the left anterior des

In [140]:
import tensorflow as tf
from tensorflow .keras.preprocessing.text import Tokenizer

In [136]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([train_content[:3000]])

In [141]:
train_content[:3000]

"4\tCatheterization laboratory events and hospital outcome with direct angioplasty for acute myocardial infarction To assess the safety of direct infarct angioplasty without antecedent thrombolytic therapy, catheterization laboratory and hospital events were assessed in consecutively treated patients with infarctions involving the left anterior descending (n = 100 patients), right (n = 100), and circumflex (n = 50) coronary arteries. The groups of patients were similar for age (left anterior descending coronary artery, 59 years; right coronary artery, 58 years; circumflex coronary artery, 62 years), patients with multivessel disease (left anterior descending coronary artery, 55%; right coronary artery, 55%; circumflex coronary artery, 64%), and patients with initial grade 0/1 antegrade flow (left anterior descending coronary artery, 79%; right coronary artery, 84%; circumflex coronary artery, 90%). Cardiogenic shock was present in eight patients with infarction of the left anterior des

In [142]:
tokenizer.word_index,len(tokenizer.word_index)

({'coronary': 1,
  'artery': 2,
  'the': 3,
  'of': 4,
  'with': 5,
  'and': 6,
  'infarction': 7,
  'patients': 8,
  'left': 9,
  'anterior': 10,
  'descending': 11,
  'in': 12,
  'right': 13,
  'circumflex': 14,
  'laboratory': 15,
  'for': 16,
  'were': 17,
  'years': 18,
  'catheterization': 19,
  'events': 20,
  'n': 21,
  'shock': 22,
  'four': 23,
  'hospital': 24,
  'direct': 25,
  'angioplasty': 26,
  'to': 27,
  'therapy': 28,
  '100': 29,
  '55': 30,
  '0': 31,
  'was': 32,
  'eight': 33,
  '16': 34,
  'renal': 35,
  'children': 36,
  'cases': 37,
  'presenting': 38,
  'features': 39,
  '4': 40,
  'outcome': 41,
  'acute': 42,
  'myocardial': 43,
  'assess': 44,
  'safety': 45,
  'infarct': 46,
  'without': 47,
  'antecedent': 48,
  'thrombolytic': 49,
  'assessed': 50,
  'consecutively': 51,
  'treated': 52,
  'infarctions': 53,
  'involving': 54,
  '50': 55,
  'arteries': 56,
  'groups': 57,
  'similar': 58,
  'age': 59,
  '59': 60,
  '58': 61,
  '62': 62,
  'multivessel':

In [143]:
for sentences in train_content[:3000].split("/n"):
  #print(sentences)
  print(tokenizer.texts_to_sequences([sentences]))

[[40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27, 44, 3, 45, 4, 25, 46, 26, 47, 48, 49, 28, 19, 15, 6, 24, 20, 17, 50, 12, 51, 52, 8, 5, 53, 54, 3, 9, 10, 11, 21, 29, 8, 13, 21, 29, 6, 14, 21, 55, 1, 56, 3, 57, 4, 8, 17, 58, 16, 59, 9, 10, 11, 1, 2, 60, 18, 13, 1, 2, 61, 18, 14, 1, 2, 62, 18, 8, 5, 63, 64, 9, 10, 11, 1, 2, 30, 13, 1, 2, 30, 14, 1, 2, 65, 6, 8, 5, 66, 67, 31, 68, 69, 70, 9, 10, 11, 1, 2, 71, 13, 1, 2, 72, 14, 1, 2, 73, 74, 22, 32, 75, 12, 33, 8, 5, 7, 4, 3, 9, 10, 11, 1, 2, 23, 5, 7, 4, 3, 13, 1, 2, 6, 23, 5, 7, 4, 3, 14, 1, 2, 76, 19, 15, 20, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 16, 87, 6, 88, 89, 90, 12, 91, 8, 5, 7, 4, 3, 9, 10, 11, 1, 2, 33, 5, 7, 4, 3, 13, 1, 2, 6, 23, 5, 7, 4, 3, 14, 1, 2, 34, 4, 34, 22, 6, 92, 4, 93, 94, 8, 95, 96, 97, 31, 98, 99, 32, 100, 12, 15, 101, 22, 102, 5, 7, 4, 3, 9, 10, 11, 1, 2, 103, 35, 104, 12, 36, 105, 37, 4, 35, 106, 12, 36, 107, 108, 27, 109, 3, 110, 38, 39, 111, 112, 113, 114, 37, 115, 116, 3, 117, 118, 18, 17, 119, 1

In [87]:
#converting supervised for nxt tect genartion

In [144]:
input_sequences = []
for sentences in train_content[:3000].split("/n"):
  #print(sentences)
  tokenize_sentence = tokenizer.texts_to_sequences([sentences])[0]

  for i in range(1,len(tokenize_sentence)):
    input_sequences.append(tokenize_sentence[:i+1])

In [145]:
input_sequences

[[40, 19],
 [40, 19, 15],
 [40, 19, 15, 20],
 [40, 19, 15, 20, 6],
 [40, 19, 15, 20, 6, 24],
 [40, 19, 15, 20, 6, 24, 41],
 [40, 19, 15, 20, 6, 24, 41, 5],
 [40, 19, 15, 20, 6, 24, 41, 5, 25],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27, 44],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27, 44, 3],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27, 44, 3, 45],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27, 44, 3, 45, 4],
 [40, 19, 15, 20, 6, 24, 41, 5, 25, 26, 16, 42, 43, 7, 27, 44, 3, 45, 4, 25],
 [40,
  19,
  15,
  20,
  6,
  24,
  41,
  5,
  25,
  26,
  16,
  42,
  43,
  7,
  27,
  44,
  3,
  45,
  4,
  25,
  46],
 [40,
  19,
  15,
  20,
  6

In [146]:
# making all senetences in same shape
# zero padding

In [147]:
max_len = max([len(x) for x in input_sequences])

In [148]:
max_len

338

In [149]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences , maxlen = 338 ,padding = "pre")

In [150]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  40,  19],
       [  0,   0,   0, ...,  40,  19,  15],
       [  0,   0,   0, ...,  19,  15,  20],
       ...,
       [  0,   0,  40, ...,  12,   3, 111],
       [  0,  40,  19, ...,   3, 111,   3],
       [ 40,  19,  15, ..., 111,   3,  17]], dtype=int32)

In [151]:
padded_input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,  40],
       [  0,   0,   0, ...,   0,  40,  19],
       [  0,   0,   0, ...,  40,  19,  15],
       ...,
       [  0,   0,  40, ...,  17,  12,   3],
       [  0,  40,  19, ...,  12,   3, 111],
       [ 40,  19,  15, ...,   3, 111,   3]], dtype=int32)

In [152]:
x = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [153]:
y

array([ 19,  15,  20,   6,  24,  41,   5,  25,  26,  16,  42,  43,   7,
        27,  44,   3,  45,   4,  25,  46,  26,  47,  48,  49,  28,  19,
        15,   6,  24,  20,  17,  50,  12,  51,  52,   8,   5,  53,  54,
         3,   9,  10,  11,  21,  29,   8,  13,  21,  29,   6,  14,  21,
        55,   1,  56,   3,  57,   4,   8,  17,  58,  16,  59,   9,  10,
        11,   1,   2,  60,  18,  13,   1,   2,  61,  18,  14,   1,   2,
        62,  18,   8,   5,  63,  64,   9,  10,  11,   1,   2,  30,  13,
         1,   2,  30,  14,   1,   2,  65,   6,   8,   5,  66,  67,  31,
        68,  69,  70,   9,  10,  11,   1,   2,  71,  13,   1,   2,  72,
        14,   1,   2,  73,  74,  22,  32,  75,  12,  33,   8,   5,   7,
         4,   3,   9,  10,  11,   1,   2,  23,   5,   7,   4,   3,  13,
         1,   2,   6,  23,   5,   7,   4,   3,  14,   1,   2,  76,  19,
        15,  20,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  16,
        87,   6,  88,  89,  90,  12,  91,   8,   5,   7,   4,   

In [56]:
# making multi class
#using one hot encoding
#[010000] [100000 ]

In [154]:
x.shape,y.shape

((337, 337), (337,))

In [155]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = len(tokenizer.word_index)+1)

In [156]:
y.shape,y

((337, 127),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [157]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten ,Dropout ,Embedding,LSTM

In [168]:
model = Sequential()
model.add(Embedding(len(tokenizer.word_index)+1,100,input_length = 338 ))
model.add(LSTM(300))
#model.add(LSTM(300))
model.add(Dense(len(tokenizer.word_index)+1,activation = "softmax"))

model.build(input_shape=(None, max_len-1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [169]:
model.compile(loss = "categorical_crossentropy",optimizer = "adam",
              metrics = ["accuracy"])

In [170]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 337, 100)       │        12,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 300)            │       481,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 127)            │        38,227 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 532,127 (2.03 MB)

 Trainable params: 532,127 (2.03 MB)

 Non-trainable params: 0 (0.00 B)

In [171]:
model.fit(x,y,epochs = 10,validation_split = 0.2)

Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 18s 2s/step - accuracy: 0.0320 - loss: 4.8359 - val_accuracy: 0.0588 - val_loss: 4.7040
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 15s 2s/step - accuracy: 0.0435 - loss: 4.5153 - val_accuracy: 0.0000e+00 - val_loss: 4.8928
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - accuracy: 0.0639 - loss: 4.4819 - val_accuracy: 0.0000e+00 - val_loss: 4.6333
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 14s 2s/step - accuracy: 0.1134 - loss: 4.3195 - val_accuracy: 0.0000e+00 - val_loss: 4.7098
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 14s 2s/step - accuracy: 0.0508 - loss: 4.2648 - val_accuracy: 0.0000e+00 - val_loss: 4.7086
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 14s 2s/step - accuracy: 0.0760 - loss: 4.1851 - val_accuracy: 0.0000e+00 - val_loss: 4.6985
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - accuracy: 0.1339 - loss: 4.1360 - val_accuracy: 0.0588 - val_loss: 4.6074
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 15s 2s/step - accuracy: 0.1366 - loss: 3.9298 - val_accuracy: 0.0735 - val_l

In [173]:
text = "hospital "
#tokenizer
token_text = tokenizer.texts_to_sequences([text])[0]
print(token_text)
#padding
padded_toekn_text = pad_sequences([token_text],maxlen = max_len -1, padding ="pre")
print(padded_toekn_text)
#predict
print(model.predict(padded_toekn_text).shape)
import numpy as np
pos = np.argmax(model.predict(padded_toekn_text))
print(np.argmax(model.predict(padded_toekn_text)))

[24]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  

In [174]:
tokenizer.word_index

{'coronary': 1,
 'artery': 2,
 'the': 3,
 'of': 4,
 'with': 5,
 'and': 6,
 'infarction': 7,
 'patients': 8,
 'left': 9,
 'anterior': 10,
 'descending': 11,
 'in': 12,
 'right': 13,
 'circumflex': 14,
 'laboratory': 15,
 'for': 16,
 'were': 17,
 'years': 18,
 'catheterization': 19,
 'events': 20,
 'n': 21,
 'shock': 22,
 'four': 23,
 'hospital': 24,
 'direct': 25,
 'angioplasty': 26,
 'to': 27,
 'therapy': 28,
 '100': 29,
 '55': 30,
 '0': 31,
 'was': 32,
 'eight': 33,
 '16': 34,
 'renal': 35,
 'children': 36,
 'cases': 37,
 'presenting': 38,
 'features': 39,
 '4': 40,
 'outcome': 41,
 'acute': 42,
 'myocardial': 43,
 'assess': 44,
 'safety': 45,
 'infarct': 46,
 'without': 47,
 'antecedent': 48,
 'thrombolytic': 49,
 'assessed': 50,
 'consecutively': 51,
 'treated': 52,
 'infarctions': 53,
 'involving': 54,
 '50': 55,
 'arteries': 56,
 'groups': 57,
 'similar': 58,
 'age': 59,
 '59': 60,
 '58': 61,
 '62': 62,
 'multivessel': 63,
 'disease': 64,
 '64': 65,
 'initial': 66,
 'grade': 67,
 

In [175]:
for word, index in tokenizer.word_index.items():
  if index == pos:
    print(word)

with


In [176]:
import time
text = "left anterior"
# for nxt 5 word
for i in range(10):
  token_text = tokenizer.texts_to_sequences([text])[0]
  padded_toekn_text = pad_sequences([token_text] ,
                                  maxlen = max_len -1, padding ="pre" )
  pos = np.argmax(model.predict(padded_toekn_text))
  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(1)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
left anterior the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
left anterior the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
left anterior the the and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
left anterior the the and and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
left anterior the the and and with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step
left anterior the the and and with the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step
left anterior the the and and with the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
left anterior the the and and with the the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
left anterior the the and and with the the the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
left anterior the the and and with the the the the and
